[browser]
gatherUsageStats = false

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#ffaa00"
backgroundColor = "#141414"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#cc8800"
font = "monospace"
